apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "hf-serve.fullname" . }}-config
  labels:
    {{- include "hf-serve.labels" . | nindent 4 }}
data:
  config.yaml: |
    {{- .Values.collection | toYaml | nindent 4 }}
